// --- --- --- 09) Integration
// Integrates the Rocky Outcrop (29) classification with the main 
// MapBiomas Cerrado native vegetation and anthropic classification. 
// Rocky Outcrop overwrites any existing class. After integration, a 
// secondary spatial filter is applied to remove tiny spurious patches 
// (≤ 6 pixels) generated by the edge overlaps.

// Define visualization parameters
var vis = {
  min: 0,
  max: 75,
  palette: require('users/mapbiomas/modules:Palettes.js').get('brazil'),
  bands: 'classification_2024'
};

// Define the input paths 
var nativeAssetPath = 'projects/ee-ipam/assets/MAPBIOMAS/LULC/CERRADO_DEV/COL_11/LANDSAT/C11-POST-CLASSIFICATION/CERRADO_C11_gp_v17_spt_v2_tp_v2_tra_v5_snv_v3_traj_v4_freq_v5_tm_v11_reg_v44_silv_v11_shp_v5_spt_v5';
var rockyAssetPath = 'projects/ee-ipam/assets/MAPBIOMAS/LULC/CERRADO_DEV/COL_11/LANDSAT/C11-ROCKY-POST-CLASSIFICATION/CERRADO_C11_rocky_gapfill_frequency_v4_spatial_v10';

// Define the base output directory path 
var root = 'projects/ee-ipam/assets/MAPBIOMAS/LULC/CERRADO_DEV/COL_11/LANDSAT/C11-POST-CLASSIFICATION/';

// Construct the exact filename for the export
var outputName  = 'CERRADO_C11_native_spt5_rocky_spt10';

// Set the temporal boundaries of the time series
var startYear = 1985;
var endYear = 2025;

// Set the native pixel resolution scale in meters (Landsat spatial resolution)
var scale = 30; 

// Define integration parameters
var forestClass = 3; 
var waterClass = 33; 
var rockyClass = 29; 
var minConnectedPixels = 6; // Maximum size of isolated patches to be smoothed
var minDiagonalForestPixels = 3; // Minimum 8-way connections to protect diagonal forest

// Load the general native vegetation and anthropic classification image stack
var nativeClassification = ee.Image(nativeAssetPath);

// Load the standalone Rocky Outcrop classification image stack
var rockyClassification = ee.Image(rockyAssetPath);

// Print the input image structures to the console for inspection
print('Input native vegetation classification', nativeClassification);
print('Input rocky outcrop classification', rockyClassification);

// Render the input layers to the map (hidden by default)
Map.addLayer(nativeClassification, vis, 'Native vegetation', false);
Map.addLayer(rockyClassification, vis, 'Rocky outcrop', false);

// Load the Cerrado classification regions vector and convert it to a binary image mask.
// This mask is strictly used to insert Water (33) as a base layer in Region 1.
var ecoregionsMask = ee.Image(1).clip(ee.FeatureCollection('projects/ee-ipam-cerrado/assets/ancillary/collection_11_classification_regions_vector'));

// Region 1 mask
// This mask must be used only to add water class 33 in Region 1.
// Do not use this mask to clip native, rocky, or the final integrated image.
var region1Fc = ee.FeatureCollection('users/dh-conciani/collection7/classification_regions/vector_v2')
                  .filter(ee.Filter.eq('mapb', 1));

var region1Mask = ee.Image(1)
                    .byte()
                    .clip(region1Fc)
                    .selfMask();
  
Map.addLayer(region1Mask, {min: 1, max: 1, palette: ['ffffff']}, 'Region 1 mask');


// Initialize an empty Earth Engine image to accumulate the integrated annual bands
var container = ee.Image([]);

// Iterate over each year in the time series to perform the integration and spatial filtering
for (var year = 1985; year <= 2025; year++) {

  var bandName = 'classification_' + year;

  // Extract annual bands without clipping by region
  var nativeYear = nativeClassification
    .select(bandName)
    .rename(bandName);

  var rockyYear = rockyClassification
    .select(bandName)
    .rename(bandName);

  // Native + Rocky integration for the entire Cerrado.
  // Rocky outcrop unconditionally overrides native classification where rocky == 29.
  var nativeRocky = nativeYear
    .where(rockyYear.eq(rockyClass), rockyClass)
    .rename(bandName);

  // Region 1 base layer with Water (Class 33).
  // Acts as the background canvas exclusively for Region 1.
  var regionBase = ee.Image(waterClass)
    .rename(bandName)
    .updateMask(region1Mask);

  // Layering (Sandwich) logic:
  // 1. Region 1 mask acts as the base (bottom layer) with Class 33.
  // 2. Native + Rocky map is placed on top, overriding the water base where data exists.
  var integratedYear = regionBase
    .blend(nativeRocky)
    .rename(bandName);

  // Compute the focal mode (majority class) within a 2-pixel square radius
  var focalMode = integratedYear
    .unmask(0)
    .focal_mode({
      radius: 2,
      kernelType: 'square',
      units: 'pixels'
    });

  // Calculate general connectivity using 4-way (orthogonal) pixel connections
  var connections = integratedYear
    .unmask(0)
    .connectedPixelCount({
      maxSize: 120,
      eightConnected: false
    });

  // Forest diagonal protection logic:
  // Thin, diagonal forest corridors might appear disconnected in 4-way checks 
  // and get falsely erased. This checks 8-way connectivity to protect them.
  var forestMask = integratedYear
    .eq(forestClass)
    .selfMask();

  var forestConnections4 = forestMask
    .connectedPixelCount({
      maxSize: 120,
      eightConnected: false
    });

  var forestConnections8 = forestMask
    .connectedPixelCount({
      maxSize: 120,
      eightConnected: true
    });

  // A forest pixel is protected if its 8-way connectivity is greater than its 4-way,
  // and it belongs to a diagonal cluster of at least 'minDiagonalForestPixels'.
  var protectForest = integratedYear
    .eq(forestClass)
    .and(forestConnections8.gt(forestConnections4))
    .and(forestConnections8.gte(minDiagonalForestPixels))
    .unmask(0);

  // Create the final spatial filter mask.
  // Target small patches (<= 6 pixels), but strictly ignore Water (33) and protected forests.
  var filterMask = connections
    .lte(minConnectedPixels)
    .and(integratedYear.neq(waterClass))
    .and(protectForest.not());

  // Apply the filter mask to the focal mode image
  var toFilter = focalMode
    .updateMask(filterMask)
    .updateMask(focalMode.neq(0));

  // Blend the smoothed patches back into the integrated image.
  // Reproject strictly to EPSG:4326 at 30m to enforce operations at the native grid.
  integratedYear = integratedYear
    .blend(toFilter)
    .reproject('EPSG:4326', null, scale)
    .rename(bandName)
    .byte();

  // Append the processed annual band to the final multi-band stack
  container = container.addBands(integratedYear);
}

// Render the final integrated classification map to the display
Map.addLayer(container, vis, 'Integrated');
print('Output integrated classification', container);

// Export as GEE asset
Export.image.toAsset({
    image: container,
    description: outputName,
    assetId: root + outputName,
    pyramidingPolicy: {'.default': 'mode' },
    region: nativeClassification.geometry(),
    scale: scale,
    maxPixels: 1e13
});
