// --- --- --- 09) Integration
// This script integrates the Rocky Outcrop (29) classification with the main 
// MapBiomas Cerrado native vegetation and anthropic classification. 
// Integration Rule: Rocky Outcrop overwrites any existing class EXCEPT Forest 
// Formation (3). After integration, a secondary spatial filter is applied 
// to remove tiny spurious patches (≤ 6 pixels) generated by the edge overlaps, 
// smoothing them with a 2-pixel focal mode. 


// Define visualization parameters
var vis = {
  min: 0,
  max: 75,
  palette: require('users/mapbiomas/modules:Palettes.js').get('brazil'),
  bands: 'classification_2024'
};

// Define the output version string for the final integrated asset
var outputVersion = '2';

// Define the input paths 
var nativeAssetPath = 'projects/ee-ipam/assets/MAPBIOMAS/LULC/CERRADO_DEV/COL_11/SENTINEL/C04-POST-CLASSIFICATION/CERRADO_C04_gapfill_v3_spt_v1_tp_v3_tra_v2_snv_v3_traj_v4_freq_v2_temp_v2_freg_v3_shp_v1_spt_v1';
var rockyAssetPath = 'projects/ee-ipam/assets/MAPBIOMAS/LULC/CERRADO_DEV/COL_11/SENTINEL/C04-ROCKY-POST-CLASSIFICATION/CERRADO_C04_rocky_gapfill_frequency_spatial_v1';

// Define the base output directory path 
var outDir = 'projects/mapbiomas-workspace/COLECAO_DEV/COLECAO10_DEV/CERRADO/SENTINEL/C03-POST-CLASSIFICATION/';

// Construct the exact filename for the export
var exportFilename = 'CERRADO_C04_native_spt1_rocky_spt1_v' + outputVersion;

// Set the starting and ending year of the processing time-series
var startYear = 2017;
var endYear = 2025;

// Set the native pixel resolution scale in meters
var scale = 10;

// Load the general native vegetation and anthropic classification image
var nativeClassification = ee.Image(nativeAssetPath);

// Load the rocky outcrop classification image
var rockyClassification = ee.Image(rockyAssetPath);

// Print the input image structures to the console for inspection
print('Input native vegetation classification', nativeClassification);
print('Input rocky outcrop classification', rockyClassification);

// Render the input layers to the map (hidden by default)
Map.addLayer(nativeClassification, vis, 'Native vegetation', false);
Map.addLayer(rockyClassification, vis, 'Rocky outcrop', false);

// Load the Cerrado ecoregions vector and convert it to a binary image mask
var ecoregionsMask = ee.Image(1).clip(ee.FeatureCollection('projects/ee-ipam-cerrado/assets/ancillary/collection_11_classification_regions_vector'));

// Initialize an empty Earth Engine image to accumulate the integrated annual bands
var container = ee.Image([]);

// Iterate over each year in the defined time series
ee.List.sequence({start: startYear, end: endYear}).getInfo().forEach(function(year) {
  
  // Extract the specific annual band from the native classification stack
  var nativeYear = nativeClassification.select(['classification_' + year]);
  
  // Extract the specific annual band from the rocky outcrop classification stack
  var rockyYear = rockyClassification.select(['classification_' + year]);
  
  // Apply Integration Rule: Overwrite the native class with Rocky Outcrop (29) UNLESS the native class is Forest (3)
  var integratedYear = nativeYear.where(nativeYear.neq(3).and(rockyYear.eq(29)), 29);
  
  // Compute the focal mode (majority class) within a 2-pixel square radius to serve as a replacement
  var focalMode = integratedYear.unmask(0).focal_mode({radius: 2, kernelType: 'square', units: 'pixels'});

  // Compute the number of contiguous connected pixels of the same class (using 4-way connections)
  var connections = integratedYear.unmask(0).connectedPixelCount({maxSize: 120, eightConnected: false});

  // Mask the focal mode image to retain only areas where the patch size is less than or equal to 6 pixels
  var toMask = focalMode.updateMask(connections.lte(6));

  // Blend the integrated image with the masked focal mode to eliminate isolated overlapping artifacts
  // Reproject strictly to EPSG:4326 at 10m to enforce neighborhood computations at the native resolution
  // Apply the ecoregions mask to ensure the final output is strictly bounded to the Cerrado
  integratedYear = integratedYear.blend(toMask).reproject('EPSG:4326', null, scale).updateMask(ecoregionsMask);

  // Append the processed and smoothed annual band to the final multi-band stack
  container = container.addBands(integratedYear);
});

// Render the final, integrated classification map to the display
Map.addLayer(container, vis, 'Integrated Classification');

// Print the resulting final integrated image structure to the console
print('Output integrated classification', container);

// Configure and execute the Earth Engine batch task to export the finalized image as an Asset
Export.image.toAsset({
  image: container,
  description: exportFilename,
  assetId: outDir + exportFilename,
  pyramidingPolicy: {'.default': 'mode'},
  region: nativeClassification.geometry(),
  scale: scale,
  maxPixels: 1e13
});

